[package]
name = "inexor-rgf-plugin-graphql-client"
description = "Inexor - Reactive Graph Flow - Plugin - GraphQL Client"
version = "0.8.0"
authors = ["Andreas Schaeffer <hanack@nooblounge.net"]
edition = "2021"
license = "MIT"

[dependencies]
async-trait = "0.1"
http = "0.2"
indradb-lib = "3"
lazy_static = "1.4"
log = { version = "0.4", features = ["std", "serde"] }
log4rs = { version = "1.0", features = ["console_appender", "file_appender", "toml_format"] }
mime_guess = "2.0"
query_interface = "0.3"
rust-embed = { version = "6.4", features = ["debug-embed", "compression"] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
uuid = { version = "1.1", features = ["serde", "v4"] }

inexor-rgf-core-di = { version = "2.0", features = ["async"], git = "https://github.com/inexorgame/inexor-rgf-core-di.git" }
inexor-rgf-core-frp = { git = "https://github.com/inexorgame/inexor-rgf-core-frp.git" }
inexor-rgf-core-model = { git = "https://github.com/inexorgame/inexor-rgf-core-model.git" }
inexor-rgf-core-plugins = { git = "https://github.com/inexorgame/inexor-rgf-core-plugins.git" }

[build-dependencies]
static-files = "0.2.3"

[package.metadata.cargo-post.dependencies]
toml = "0.5"
serde = { version = "1.0", features = [ "derive" ] }
glob = "0.3"

[lib]
# Plugins use crate-type cdylib
# https://doc.rust-lang.org/reference/linkage.html
# https://users.rust-lang.org/t/what-is-the-difference-between-dylib-and-cdylib/28847/3
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
strip = "symbols"
