[package]
name = "inexor-rgf-model-base"
description = "Inexor - Reactive Graph Flow - Model - Base"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
indradb-lib = { workspace = true }
lazy_static = { workspace = true }
license = { workspace = true }
paste = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
strum_macros = { workspace = true }

inexor-rgf-core-model = { workspace = true }

[lib]
crate-type = ["lib"]
