name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - "plugins/*/crates/**/*.rs"
      - "plugins/**/crates/**/Cargo.toml"
      - "Cargo.toml"
  pull_request:
    branches: [ main ]
    paths:
      - "plugins/*/crates/**/*.rs"
      - "plugins/**/crates/**/Cargo.toml"
      - "Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd plugins/graphql-client/web install
      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd plugins/graphql-schema-visualization/web install
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
