name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install Yarn
      uses: borales/actions-yarn@v4
      with:
        cmd: --cwd plugins/inexor-rgf-plugin-graphql-client/web install
    - name: Install Yarn
      uses: borales/actions-yarn@v4
      with:
        cmd: --cwd plugins/inexor-rgf-plugin-graphql-schema-visualization/web install
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  rustfmt:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: rustfmt
      - run: cargo fmt --all -- --check

  codecov-tarpaulin:
    name: Generate code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd plugins/inexor-rgf-plugin-graphql-client/web install
      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd plugins/inexor-rgf-plugin-graphql-schema-visualization/web install
      - uses: actions-rs/tarpaulin@v0.1
        with:
          args: --all-features
      # Note: closed-source code needs to provide a token,
      # but open source code does not.
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
