name: Rust

on:
  push:
    branches: [ main ]
    paths:
      - "plugins/*/crates/**/*.rs"
      - "plugins/**/crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/rust.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "plugins/*/crates/**/*.rs"
      - "plugins/**/crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/rust.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd plugins/graphql-client/web install
      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: --cwd plugins/graphql-schema-visualization/web install
      - name: Build (Release Mode)
        uses: actions-rs/cargo@v1
        with:
          command: "build"
          args: "--release --verbose"
      - name: Test (Release Mode)
        uses: actions-rs/cargo@v1
        with:
          command: "test"
          args: "--release --verbose"
